/**
 * Rock Paper Scissors
 * Randomly resolve rock paper scissors games
 *
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
export interface GeekModeResponse {
    opponentHand?: GeekModeResponse.OpponentHandEnum;
    result?: GeekModeResponse.ResultEnum;
}
export declare namespace GeekModeResponse {
    type OpponentHandEnum = 'ROCK' | 'PAPER' | 'SCISSORS' | 'LIZARD' | 'SPOCK';
    const OpponentHandEnum: {
        ROCK: OpponentHandEnum;
        PAPER: OpponentHandEnum;
        SCISSORS: OpponentHandEnum;
        LIZARD: OpponentHandEnum;
        SPOCK: OpponentHandEnum;
    };
    type ResultEnum = 'VICTORY' | 'DEFEAT' | 'DRAW';
    const ResultEnum: {
        VICTORY: ResultEnum;
        DEFEAT: ResultEnum;
        DRAW: ResultEnum;
    };
}
