/**
 * Rock Paper Scissors
 * Randomly resolve rock paper scissors games
 *
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
export interface Link {
    href?: string;
    templated?: boolean;
}
